import type { CapacitorConfig } from '@capacitor/cli';

// Native shell config for the iOS / Android builds.
//
// NOTE ON `server`: there is deliberately no `server.url` here. Pointing the
// WebView at app.launchsession.co.uk would make every Vercel deploy land in the
// app instantly, but Apple rejects thin URL wrappers under guideline 4.2, and a
// remote origin also breaks WebAuthn and Associated Domains. The web build is
// bundled instead (`npm run build && npx cap sync`), and fast iteration comes
// from live-reload in development, not from a remote origin in production.
//
// For live-reload during development, do NOT edit this file. Run:
//   npx cap run ios --livereload --external
// which injects the dev-server URL at run time and leaves the committed config
// alone, so a dev URL can never be shipped by accident.

const config: CapacitorConfig = {
  appId: 'uk.co.launchsession.app',
  appName: 'LaunchSession',

  // CRA emits to build/. Must match, or `cap sync` copies nothing.
  webDir: 'build',

  ios: {
    // The app has its own header treatment and handles safe areas in CSS.
    contentInset: 'never',
    // Match the app shell rather than flashing white on overscroll.
    backgroundColor: '#0B1B33',
    // Deliberately not setting limitsNavigationsToAppBoundDomains: without a
    // declared WKAppBoundDomains list it treats our own domain as external and
    // ejects to Safari. Links to other sites open externally regardless.
  },

  android: {
    backgroundColor: '#0B1B33',
    // Release builds only; keeps `adb`-attached debugging off store builds.
    webContentsDebuggingEnabled: false,
  },

  plugins: {
    // Splash is dismissed explicitly once React has mounted, otherwise the
    // native splash tears down first and the user sees a blank WebView while
    // the JS bundle parses.
    SplashScreen: {
      launchAutoHide: false,
      backgroundColor: '#0B1B33',
    },
  },
};

export default config;
